spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/triple-mileage
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        # use_sql_comments: true
    open-in-view: false

server:
  error:
    include-message: always

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace
